### ISSUE TITLE
Incompatible With IDE Build 242+

### ISSUE THREAD

**Issue by CCattano** [vlad-d/racing-progress-bar#19]
I've recently updated my WebStorm IDE and Racing Loading Bar is no longer compatible with my IDE.

From what I can tell the plugin is based on a build version that is considered too old to work with this newest build version I've updated to.

Here are the details of my WebStorm installation as copy/pasted from the IDE itself.

```
WebStorm 2024.2.1
Build #WS-242.21829.149, built on August 29, 2024
Runtime version: 21.0.3+13-b509.11 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.windows.WToolkit
Windows 10.0
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2048M
Cores: 24
Registry:
  debugger.new.tool.window.layout=true
  documentation.show.toolbar=true
  ide.experimental.ui=true
  i18n.locale=
  terminal.new.ui=true
Non-Bundled Plugins:
  com.jetbrains.space (242.21829.142)
  com.github.lonre.gruvbox-intellij-theme (0.6.2)
  org.jetbrains.plugins.gitlab (242.21829.162)
  org.jetbrains.plugins.github (242.21829.162)
  com.github.copilot (1.5.21.6667)
```

Here is a screencap of the error I am seeing in WebStorm's plugin manager.

![image](https://github.com/user-attachments/assets/e282d5ae-a0a9-4e72-98e2-467eff57124e)

If there's any more information I can provide please let me know!

**Comment by vlad-d** [comment]
Hi @CCattano! I've updated the plugin and now it works with the newest versions of IntelliJ IDEs. Sorry for taking a bit longer than expected 🙏
